#!/usr/bin/env python3
"""Generate a Q2RTX-owned FSR3 Vulkan blob table.

The manifest is deliberately independent of the FidelityFX SDK DXIL blob
sources.  Each entry names a SPIR-V file and its reflected FfxShaderBlob
binding metadata; the generator embeds the bytes so runtime loading has no
filesystem dependency.
"""

import json
import pathlib
import sys


def c_string(value):
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def emit_bytes(data):
    if not data:
        return "{}"
    return "{ " + ", ".join(f"0x{x:02x}" for x in data) + " }"


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: generate_blob_table.py MANIFEST OUTPUT")
    manifest_path, output_path = map(pathlib.Path, sys.argv[1:])
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("version") != 1:
        raise SystemExit("unsupported FSR3 Vulkan blob manifest version")

    rows = []
    for item in manifest.get("permutations", []):
        required = ("pass", "options", "spirv", "entry")
        missing = [key for key in required if key not in item]
        if missing:
            raise SystemExit("manifest entry missing: " + ", ".join(missing))
        spirv_path = manifest_path.parent / item["spirv"]
        data = spirv_path.read_bytes()
        if len(data) % 4 or data[:4] != b"\x03\x02\x23\x07":
            raise SystemExit(f"{spirv_path}: not a valid SPIR-V module")
        bindings = item.get("bindings", {})
        if not bindings and item.get("metadata"):
            metadata = json.loads(pathlib.Path(item["metadata"]).read_text(encoding="utf-8"))
            bindings = {kind: [] for kind in ("cbv", "srvTextures", "uavTextures", "srvBuffers", "uavBuffers", "samplers")}
            for resource in metadata.get("resources", []):
                kind = resource.get("kind")
                if kind in bindings:
                    bindings[kind].append(resource)
        if not data or not any(bindings.values()):
            raise SystemExit(f"{spirv_path}: blob row has no binding metadata")
        rows.append((item, data, bindings))

    if not rows:
        raise SystemExit("FSR3 Vulkan blob manifest contains no supported passes")

    out = ["/* Generated by generate_blob_table.py; do not edit. */", "#pragma once", "", "#include <stdint.h>", "", "typedef struct Fsr3VkptGeneratedBindings {", "    const char** names;", "    const uint32_t* slots;", "    const uint32_t* counts;", "    const uint32_t* spaces;", "    uint32_t count;", "} Fsr3VkptGeneratedBindings;", "", "typedef struct Fsr3VkptGeneratedBlob {", "    uint32_t pass;", "    uint32_t options;", "    const uint8_t* bytes;", "    uint32_t size;", "    const char* entry;", "    Fsr3VkptGeneratedBindings cbv;", "    Fsr3VkptGeneratedBindings srvTextures;", "    Fsr3VkptGeneratedBindings uavTextures;", "    Fsr3VkptGeneratedBindings srvBuffers;", "    Fsr3VkptGeneratedBindings uavBuffers;", "    Fsr3VkptGeneratedBindings samplers;", "} Fsr3VkptGeneratedBlob;", ""]
    for index, (item, data, bindings) in enumerate(rows):
        out += [f"static const uint8_t fsr3_vkpt_spirv_{index}[] = {emit_bytes(data)};"]
        for kind in ("cbv", "srvTextures", "uavTextures", "srvBuffers", "uavBuffers", "samplers"):
            values = bindings.get(kind, [])
            out.append(f"static const char* fsr3_vkpt_{kind}_names_{index}[] = {{ " + ", ".join(c_string(b["name"]) for b in values) + " };")
            out.append(f"static const uint32_t fsr3_vkpt_{kind}_slots_{index}[] = {{ " + ", ".join(str(b["binding"]) for b in values) + " };")
            out.append(f"static const uint32_t fsr3_vkpt_{kind}_counts_{index}[] = {{ " + ", ".join(str(b.get("count", 1)) for b in values) + " };")
            out.append(f"static const uint32_t fsr3_vkpt_{kind}_spaces_{index}[] = {{ " + ", ".join(str(b.get("space", 0)) for b in values) + " };")
        out.append("")
    out.append(f"static const Fsr3VkptGeneratedBlob fsr3_vkpt_generated_blobs[{len(rows) or 1}] = {{")
    for index, (item, data, bindings) in enumerate(rows):
        args = [item["pass"], item["options"], f"fsr3_vkpt_spirv_{index}", len(data), c_string(item["entry"])]
        for kind in ("cbv", "srvTextures", "uavTextures", "srvBuffers", "uavBuffers", "samplers"):
            values = bindings.get(kind, [])
            args += ["{ fsr3_vkpt_%s_names_%d, fsr3_vkpt_%s_slots_%d, fsr3_vkpt_%s_counts_%d, fsr3_vkpt_%s_spaces_%d, %d }" % (kind, index, kind, index, kind, index, kind, index, len(values))]
        out.append("    { " + ", ".join(map(str, args)) + " },")
    if not rows:
        out.append("    { 0, 0, 0, 0, 0, { 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0 }, { 0, 0, 0, 0, 0 } },")
    out += ["};", f"static const uint32_t fsr3_vkpt_generated_blob_count = {len(rows)};", ""]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(out), encoding="utf-8")


if __name__ == "__main__":
    main()
